tz_home_site:
    resource: "@FrontSiteBundle/Resources/config/routing/home.yml"
    prefix:   /

tz_membres_liste:
  resource: "@FrontSiteBundle/Resources/config/routing/membres.yml"
  prefix:     /membres

tz_article:
  resource: "@FrontSiteBundle/Resources/config/routing/article.yml"
  prefix:     /article