front_site:
    resource: "@FrontSiteBundle/Resources/config/routing.yml"
    prefix:   /

app_file:
    resource: '@AdminBundle/Resources/config/routing.yml'
    prefix:   /admin

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

